### ISSUE TITLE
We need a .gitignore

### ISSUE THREAD

**Issue by neugens** [c3d/unsubsquirrel#3]
Hi!

Please, considering merging this patch to add the .gitignore file!

Cheers,
Mario

From 08460d3c8a8359f2bf8f3aaa8295d0fde4bfbb3a Mon Sep 17 00:00:00 2001
From: neugens <neugens@redhat.com>
Date: Fri, 6 Sep 2019 11:43:05 +0200
Subject: [PATCH] Add .gitignore

---
 .gitignore | 3 +++
 1 file changed, 3 insertions(+)
 create mode 100644 .gitignore

diff --git a/.gitignore b/.gitignore
new file mode 100644
index 0000000..6e50627
--- /dev/null
+++ b/.gitignore
@@ -0,0 +1,3 @@
+.logs/
+.objects/
+unsubsquirrel
-- 
2.18.1

**Comment by c3d** [comment]
Done, thanks.
